// Define event types with colors
export const EVENT_TYPES = {
  "Design Review": "#FFEBEE",
  Meeting: "#FFF8E1",
  Discussion: "#F3E5F5",
  "Market Research": "#E8F5E9",
  "New Goals": "#FFE0B2",
};

// Sample events data
export const INITIAL_EVENTS = [
  {
    id: "1",
    title: "Design Review",
    start: "2025-04-03",
    backgroundColor: EVENT_TYPES["Design Review"],
    borderColor: EVENT_TYPES["Design Review"],
  },
  {
    id: "2",
    title: "Meeting",
    start: "2025-04-05",
    backgroundColor: EVENT_TYPES["Meeting"],
    borderColor: EVENT_TYPES["Meeting"],
  },
  {
    id: "3",
    title: "Design Review",
    start: "2025-04-08",
    backgroundColor: EVENT_TYPES["Design Review"],
    borderColor: EVENT_TYPES["Design Review"],
  },
  {
    id: "4",
    title: "Design Review",
    start: "2025-04-15",
    backgroundColor: EVENT_TYPES["Design Review"],
    borderColor: EVENT_TYPES["Design Review"],
  },
  {
    id: "5",
    title: "Discussion",
    start: "2025-04-15",
    backgroundColor: EVENT_TYPES["Discussion"],
    borderColor: EVENT_TYPES["Discussion"],
  },
  {
    id: "6",
    title: "Market Research",
    start: "2025-04-14",
    backgroundColor: EVENT_TYPES["Market Research"],
    borderColor: EVENT_TYPES["Market Research"],
  },
  {
    id: "7",
    title: "Discussion",
    start: "2025-04-14",
    backgroundColor: EVENT_TYPES["Discussion"],
    borderColor: EVENT_TYPES["Discussion"],
  },
  {
    id: "8",
    title: "Design Review",
    start: "2025-04-19",
    backgroundColor: EVENT_TYPES["Design Review"],
    borderColor: EVENT_TYPES["Design Review"],
  },
  {
    id: "9",
    title: "New Goals",
    start: "2025-04-19",
    backgroundColor: EVENT_TYPES["New Goals"],
    borderColor: EVENT_TYPES["New Goals"],
  },
  {
    id: "10",
    title: "Meeting",
    start: "2023-04-22",
    backgroundColor: EVENT_TYPES["Meeting"],
    borderColor: EVENT_TYPES["Meeting"],
  },
  {
    id: "11",
    title: "Design Review",
    start: "2023-04-22",
    backgroundColor: EVENT_TYPES["Design Review"],
    borderColor: EVENT_TYPES["Design Review"],
  },
  {
    id: "12",
    title: "Meeting",
    start: "2023-04-29",
    backgroundColor: EVENT_TYPES["Meeting"],
    borderColor: EVENT_TYPES["Meeting"],
  },
  {
    id: "13",
    title: "Design Review",
    start: "2023-04-29",
    backgroundColor: EVENT_TYPES["Design Review"],
    borderColor: EVENT_TYPES["Design Review"],
  },
  {
    id: "14",
    title: "New Goals",
    start: "2023-04-29",
    backgroundColor: EVENT_TYPES["New Goals"],
    borderColor: EVENT_TYPES["New Goals"],
  },
  {
    id: "15",
    title: "Discussion",
    start: "2023-04-29",
    backgroundColor: EVENT_TYPES["Discussion"],
    borderColor: EVENT_TYPES["Discussion"],
  },
  {
    id: "16",
    title: "Meeting",
    start: "2023-04-02",
    backgroundColor: EVENT_TYPES["Meeting"],
    borderColor: EVENT_TYPES["Meeting"],
  },
  {
    id: "17",
    title: "New Goals",
    start: "2025-04-07",
    backgroundColor: EVENT_TYPES["New Goals"],
    borderColor: EVENT_TYPES["New Goals"],
  },
  {
    id: "18",
    title: "Discussion",
    start: "2025-04-04",
    backgroundColor: EVENT_TYPES["Discussion"],
    borderColor: EVENT_TYPES["Discussion"],
  },
  {
    id: "19",
    title: "Discussion",
    start: "2025-04-06",
    backgroundColor: EVENT_TYPES["Discussion"],
    borderColor: EVENT_TYPES["Discussion"],
  },
  {
    id: "20",
    title: "Discussion",
    start: "2025-04-05",
    backgroundColor: EVENT_TYPES["Discussion"],
    borderColor: EVENT_TYPES["Discussion"],
  },
];
